---
version: "2.1"
services:
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    build: .
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    ports:
      - "10.20.20.3:8191:8191"
    restart: unless-stopped
    networks:
      - no-internet
networks:
  no-internet:
    name: php-rabbitmq
    driver: bridge
#        internal: true
